#include "circt/Dialect/Foo/FooDialect.h"
#include "circt/Dialect/Foo/FooOps.h"

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/Foo/Foo.cpp.inc"
